//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentService
    {
        public int AppointmentServID { get; set; }
        public int AppointmentID { get; set; }
        public int UserID { get; set; }
        public int VehicleID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
