//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amms.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }

        public int InvoiceID { get; set; }
        public decimal Total { get; set; }
        public System.DateTime InvDate { get; set; }
        public string InvTime { get; set; }
        public string PayType { get; set; }
        public int UserID { get; set; }
        public int VehicleID { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }

        public string FirstName { get; set; }
        public string VehicleNumber { get; set; }

        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
