//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int DetailID { get; set; }
        public string ItemServiceName { get; set; }
        public decimal Price { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public int Qty { get; set; }
        public decimal Total { get; set; }
        public int UnitID { get; set; }
        public string Remarks { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
        public virtual Service Service { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
