//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_details
    {
        public int InvoiceID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string InvDate { get; set; }
        public string InvTime { get; set; }
        public Nullable<int> PayType { get; set; }
        public int UserID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string VehicleNumber { get; set; }
        public string FirstName { get; set; }
        public string ServiceName { get; set; }
    }
}
