//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockID { get; set; }
        public Nullable<int> AvailQty { get; set; }
        public Nullable<int> MinOrderQty { get; set; }
        public Nullable<int> DamageQty { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<int> ItemID { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
